name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check Dashmap
        run: cargo check --no-default-features --features dashmap --verbose
      - name: Check cht
        run: cargo check --no-default-features --features cht --verbose
      - name: Check logging and tls
        run: cargo check --features logging,tls --verbose